name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install Dependencies
      run: |
        npm ci
        cd client && npm ci
    
    - name: Run Linting
      run: |
        npm run lint
        cd client && npm run lint
    
    - name: Run Tests with Coverage
      run: |
        npm run test:coverage
        cd client && npm run test:coverage
      env:
        CI: true
    
    - name: Upload Server Coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: server
        directory: ./coverage
    
    - name: Upload Client Coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: client
        directory: ./client/coverage 